base:
    seed: &seed 42
model:
    type: Llama
    path: meta-llama/Llama-2-7b-hf
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: ../cache/data/calib/pileval
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: pileval_awq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: [wikitext2, c4]
    download: False
    path: ../cache/data/eval
    bs: 1
    inference_per_block: False
    seq_len: 2048
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: False
        granularity: per_channel
        group_size: -1
        calib_algo: learnable
    act:
        bit: 4
        symmetric: False
        granularity: per_token
    special:
        trans: True
        weight_clip: True
        save_scale: True
        clip_version: v2
        scale_path: ../cache/activations/L2_7b/awq_w4a4
        save_clip: True
        clip_path: ../cache/activations/L2_7b/awq_w4a4
save:
    save_fp: False
    save_lightllm: False
    save_vllm: False
    save_trans: False