base:
    seed: &seed 42
model:
    type: Llama
    path: meta-llama/Llama-2-7b-hf
    torch_dtype: auto
calib:
    name: c4
    download: False
    n_samples: 512
    path: ../cache/data/calib/c4
    bs: 1
    seq_len: 2048
    preproc: c4_gptq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: [wikitext2, c4]
    download: False
    path: ../cache/data/eval
    bs: 1
    seq_len: 2048
    inference_per_block: False
    tasks: piqa,arc_easy,arc_challenge,hellaswag,winogrande
quant:
    method: TesseraQ
    weight:
        bit: 8
        symmetric: False
        granularity: per_channel
        group_size: -1
        calib_algo: minmax
    act:
        bit: 8
        symmetric: False
        granularity: per_token
        ste_all: True
    special:
        lr: 0.001
        iterations: 250
        wd: 0.0
        batch_size: 4
        deactive_amp: False
        aug_loss: False
        optimize_scale: True
        scale_lr: 0.001
        thresholds: [0.75, 0.5, 0.375, 0.25, 0.125, 0.09, 0.06, 0.04, 0.02, 0.005]
        weight_clip: True
        load_transform: True
        clip_version: v1
        reduce_memory: False
        scale_path: ../cache/activations/L2_7b/awq_w8a8
        clip_path: ../cache/activations/L2_7b/awq_w8a8
    quant_out: True
save:
    save_fp: False
    save_trans: False
    save_lightllm: False
    save_autogptq: False